spring:
  application:
    name: config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lersure/springcloud-config.git #配置文件所在仓库
          username: 1971496117@qq.com
          password: wqz**10086
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录
server:
  port: 3301
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:3300/eureka/


